return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      preset = "classic",
      icons = {
        mappings = false,
      },
      spec = {
        { "<leader>c", group = "code" },
        { "<leader>f", group = "find" },
        { "<leader>g", group = "git" },
        { "g", group = "goto", mode = { "n", "v" } },
        { "[", group = "previous", mode = { "n", "v" } },
        { "]", group = "next", mode = { "n", "v" } },

        { "gO", desc = "Document symbols" },
        { "gra", desc = "Code actions", mode = { "n", "v" } },
        { "gri", desc = "Goto implementation" },
        { "grn", desc = "Rename symbol" },
        { "grr", desc = "Goto references" },
        { "grt", desc = "Goto type definition" },

        { "[b", desc = "Previous buffer" },
        { "]b", desc = "Next buffer" },
        { "[l", desc = "Previous location item" },
        { "]l", desc = "Next location item" },
        { "[q", desc = "Previous quickfix item" },
        { "]q", desc = "Next quickfix item" },
        { "[t", desc = "Previous tab" },
        { "]t", desc = "Next tab" },

        { "g%", hidden = true, mode = { "n", "v" } },
        { "[%", hidden = true, mode = { "n", "v" } },
        { "]%", hidden = true, mode = { "n", "v" } },
        { "[A", hidden = true },
        { "]A", hidden = true },
        { "[B", hidden = true },
        { "]B", hidden = true },
        { "[L", hidden = true },
        { "]L", hidden = true },
        { "[Q", hidden = true },
        { "]Q", hidden = true },
        { "[T", hidden = true },
        { "]T", hidden = true },
        { "[<C-L>", hidden = true },
        { "]<C-L>", hidden = true },
        { "[<C-Q>", hidden = true },
        { "]<C-Q>", hidden = true },
        { "[<C-T>", hidden = true },
        { "]<C-T>", hidden = true },
      },
    },
  },
}
